annealing_epochs: 600
betas: !!python/tuple
- 0.9
- 0.999
cf_elbo_type: -1
clip_norm: 100.0
crop_size: !!python/tuple
- 224
- 224
dec_filters:
- 512
- 256
- 128
- 64
- 32
decoder_cov_rank: 10
decoder_type: independent_var
delta: 1.0e-16
div_factor: 25.0
enc_filters:
- 32
- 64
- 128
- 256
- 512
eta: 1.0
experiment: SVIExperiment
final_div_factor: 10000.0
flow_clip_norm: 1.0
head_filters:
- 1
hierarchical_div: 64
hierarchical_layers:
- 1
- 3
- 5
laplace_likelihood: true
latent_dim: 100
logstd_init: -5
logstd_weight_decay: 0.01
lr: 0.0005
lrd: 0.9999
max_annealing_factor:
- 4.4
- 1.1
- 1.0
min_annealing_factor:
- 1.0
- 1.0
- 0.0
model: ConditionalHierarchicalFlowVISEM
n_epochs: 2000
n_posterior_flows: 1
n_prior_flows: 0
num_convolutions: 3
num_sample_particles: 32
num_svi_particles: 4
pct_start: 0.1
pgm_clip_norm: 10.0
pgm_lr: 0.0025
posterior_components: 1
preprocessing: realnvp
prior_components: 1
pseudo3d: true
resize: !!python/tuple
- 128
- 128
sample_img_interval: 5
t: 0.1
test_batch_size: 320
test_csv: /iacl/pg20/jacobr/calabresi/png3d/csv/test_png.csv
tracegraph_elbo: false
train_batch_size: 342
train_crop_type: random
train_csv: /iacl/pg20/jacobr/calabresi/png3d/csv/train_png.csv
use_adagrad_rmsprop: false
use_autoregressive: true
use_cf_guide: false
use_exponential_lr: false
use_nvae: false
use_spectral_norm: false
use_spline: false
use_stable: false
use_swish: true
use_upconv: false
use_weight_norm: true
valid_csv: /iacl/pg20/jacobr/calabresi/png3d/csv/valid_png.csv
validate: false
verbosity: 0
weight_decay: 1.0e-05
